### ISSUE TITLE
ImportError: cannot import name 'tensor' from 'tensorflow.python.framework ' error fromTensorflow object detection api model_builder_tf2_test.py

### ISSUE THREAD

**Issue by OscarB11** [tensorflow/models#11196]
[ImportError: cannot import name 'tensor' from 'tensorflow.python.framework ' error fromTensorflow object detection api model_builder_tf2_test.py](https://stackoverflow.com/questions/78368737/importerror-cannot-import-name-tensor-from-tensorflow-python-framework-err)

I get this error when running the model_builder_tf2_test.py file after installing the object detection API 

I got the file to pass with tensorflow 2.15 but when I tried again in different environment using tensorflow 2.10 for the GPU support  this error was shown 

How do I get it to pass with tensorflow 2.10?

full error message below 

2024-04-22 20:39:25.792930: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-04-22 20:39:25.793198: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\Tensorflow\models\research\object_detection\builders\model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\builders\model_builder.py", line 70, in <module>
    from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\models\ssd_efficientnet_bifpn_feature_extractor.py", line 35, in <module>
    from official.legacy.image_classification.efficientnet import efficientnet_model
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_models_official-2.16.0-py3.9.egg\official\legacy\image_classification\efficientnet\efficientnet_model.py", line 30, in <module>
    import tensorflow as tf, tf_keras
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\__init__.py", line 3, in <module>
    from tf_keras import __internal__
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\__internal__\__init__.py", line 3, in <module>
    from tf_keras.__internal__ import backend
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\__internal__\backend\__init__.py", line 3, in <module>
    from tf_keras.src.backend import _initialize_variables as initialize_variables
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\src\__init__.py", line 21, in <module>
    from tf_keras.src import applications
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\src\applications\__init__.py", line 18, in <module>
    from tf_keras.src.applications.convnext import ConvNeXtBase
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\src\applications\convnext.py", line 28, in <module>
    from tf_keras.src import backend
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\src\backend.py", line 35, in <module>
    from tf_keras.src.engine import keras_tensor
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\src\engine\keras_tensor.py", line 19, in <module>
    from tf_keras.src.utils import object_identity
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\src\utils\__init__.py", line 53, in <module>
    from tf_keras.src.utils.feature_space import FeatureSpace
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\src\utils\feature_space.py", line 20, in <module>
    from tf_keras.src.engine import base_layer
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\src\engine\base_layer.py", line 35, in <module>
    from tf_keras.src.dtensor import lazy_variable
  File "c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tf_keras\src\dtensor\lazy_variable.py", line 23, in <module>
    from tensorflow.python.framework import tensor
ImportError: cannot import name 'tensor' from 'tensorflow.python.framework' (c:\Users\besto\Documents\Local vscode\Tensorflow Object Detection GPU\TFODCourse\tfodgpu\lib\site-packages\tensorflow\python\framework\__init__.py)

**Comment by Hathamwang** [comment]
I also had the same problem, can you tell me how your problem was solved

**Comment by OscarB11** [comment]
I didnt exactly solve it but I did find a workaround. Using tensorflow version 2.13 fixed the error but this version doesn't support the GPU.

**Comment by Chathura-Ranasinghe** [comment]
I faced the same issue using tensorflow version 2.10, the latest version that supports GPU accessorization in Windows native.

**Comment by MaahinVPanchal** [comment]
I am still facing the issue when test the installation
ImportError: cannot import name 'tensor' from 'tensorflow.python.framework' (D:\anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\__init__.py)

**Comment by MaahinVPanchal** [comment]
> I didnt exactly solve it but I did find a workaround. Using tensorflow version 2.13 fixed the error but this version doesn't support the GPU.

you can follow this video for gpu support

https://www.youtube.com/watch?v=NrJz3ACosJA
