### ISSUE TITLE
Resnet_v1_50 export_inferenc.py failed

### ISSUE THREAD

**Issue by vishalghor** [tensorflow/models#2356]
Hi all,

I was trying to fine tune resnet_v1_50 on flowers dataset using the script present in scripts folder 
./finetune_resnet_v1_50_flowers.sh
But it stopped after the following commands in script:
1.`python download_and_convert_data.py \
  --dataset_name=flowers \
--dataset_dir=${DATASET_DIR}`
2.`python train_image_classifier.py \
  --train_dir=${TRAIN_DIR} \
  --dataset_name=flowers \
  --dataset_split_name=train \
  --dataset_dir=${DATASET_DIR} \
  --model_name=resnet_v1_50 \
  --checkpoint_path=${PRETRAINED_CHECKPOINT_DIR}/resnet_v1_50.ckpt \
  --checkpoint_exclude_scopes=resnet_v1_50/logits \
  --trainable_scopes=resnet_v1_50/logits \
  --max_number_of_steps=3000 \
  --batch_size=32 \
  --learning_rate=0.01 \
  --save_interval_secs=60 \
  --save_summaries_secs=60 \
  --log_every_n_steps=100 \
  --optimizer=rmsprop \
--weight_decay=0.00004`
3.`# Run evaluation.
python eval_image_classifier.py \
  --checkpoint_path=${TRAIN_DIR} \
  --eval_dir=${TRAIN_DIR} \
  --dataset_name=flowers \
  --dataset_split_name=validation \
  --dataset_dir=${DATASET_DIR} \
--model_name=resnet_v1_50`
4.It stopped here: `# Fine-tune all the new layers for 1000 steps.
python train_image_classifier.py \
  --train_dir=${TRAIN_DIR}/all \
  --dataset_name=flowers \
  --dataset_split_name=train \
  --dataset_dir=${DATASET_DIR} \
  --checkpoint_path=${TRAIN_DIR} \
  --model_name=resnet_v1_50 \
  --max_number_of_steps=1000 \
  --batch_size=32 \
  --learning_rate=0.001 \
  --save_interval_secs=60 \
  --save_summaries_secs=60 \
  --log_every_n_steps=100 \
  --optimizer=rmsprop \
  --weight_decay=0.00004
`
i am getting log as :INFO:tensorflow:Summary name /clone_loss is illegal; using clone_loss instead.
INFO:tensorflow:Ignoring --checkpoint_path because a checkpoint already exists in /tmp/flowers-models/resnet_v1_50/all
2017-09-08 09:00:40.490701: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
INFO:tensorflow:Restoring parameters from /tmp/flowers-models/resnet_v1_50/all/model.ckpt-0
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path /tmp/flowers-models/resnet_v1_50/all/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
Killed

when try to run the export_inference.py for resnet_v1_50:
`python export_inference_graph.py --alsologtostderr --model_name=resnet_v1_50 --output_file=/tmp/resnet_v1_50_inf.pb`
i get the following error:

> Traceback (most recent call last):
  File "export_inference_graph.py", line 121, in <module>
    tf.app.run()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "export_inference_graph.py", line 103, in main
    FLAGS.dataset_dir)
  File "/home/ubuntu/tensorflow/models/slim/datasets/dataset_factory.py", line 57, in get_dataset
    reader)
  File "/home/ubuntu/tensorflow/models/slim/datasets/imagenet.py", line 183, in get_split
    labels_to_names = create_readable_names_for_imagenet_labels()
  File "/home/ubuntu/tensorflow/models/slim/datasets/imagenet.py", line 90, in create_readable_names_for_imagenet_labels
    filename, _ = urllib.request.urlretrieve(synset_url)
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

What could be the issue.And how to finetune the same model for custom dataset?

thanks and regards

**Comment by cy89** [comment]
Any chance you're running on an older version of TF? #8552 looks superficially similar (at least about the clone_loss error message), but was resolved in a later version.


Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by vishalghor** [comment]
Hi all,@cy89,

- **Using a stock example from models/slim**
- **OS:Linux Ubuntu 14.04**
- **TensorFlow Installed from Binary**
- **Tensorflow Version 1.2**
- **Python version : 2.7.6**
- **CUDA: NA**
- **GPU : NA (installed for CPU)**
- **command : $python export_inference_graph.py    --model_name=inception_v3    --output_file=/tmp/inception_v3_inf_graph.pb**

Sorry for not following the new issue template.
Error Log:

> Traceback (most recent call last):
  File "export_inference_graph.py", line 121, in <module>
    tf.app.run()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "export_inference_graph.py", line 103, in main
    FLAGS.dataset_dir)
  File "/home/ubuntu/tensorflow/examples/models/slim/datasets/dataset_factory.py", line 57, in get_dataset
    reader)
  File "/home/ubuntu/tensorflow/examples/models/slim/datasets/imagenet.py", line 183, in get_split
    labels_to_names = create_readable_names_for_imagenet_labels()
  File "/home/ubuntu/tensorflow/examples/models/slim/datasets/imagenet.py", line 90, in create_readable_names_for_imagenet_labels
    filename, _ = urllib.request.urlretrieve(synset_url)
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 8] _ssl.c:510: EOF occurred in violation of protocol



Kindly help me in resolving this issue.
What could be the possible cause of it?

Thanks and regards

**Comment by cy89** [comment]
@vishalghor Could you please give TF 1.3 a try instead, and see if the problem goes away?

**Comment by vishalghor** [comment]
Hi @cy89  i will try TF 1.3 and check if the  problem goes  away.i will update soon on the same after the check.

**Comment by vishalghor** [comment]
hi @cy89 ,

I tried using TF 1.3(latest version) with same commands.
The issue still persists.

**Comment by drpngx** [comment]
Sorry this fell through the cracks. Did you try with the latest (1.4) version?

**Comment by wt-huang** [comment]
Closing this issue due to inactivity, feel free to reopen if this is still an issue.
