### ISSUE TITLE
TF-models project is broken on Bazel CI

### ISSUE THREAD

**Issue by vladmos** [tensorflow/models#2822]
Bazel CI for tensorflow/models/syntaxnet is broken by 4364390adbf16b57c093a05217897831f48da7d3: https://ci.bazel.io/job/tf_models_syntaxnet/

`Unexpected error reading .blazerc file '/home/ci/workspace/tf_models_syntaxnet-variation=,node=ubuntu_16.04-x86_64/research/syntaxnet/tensorflow/.tf_configure.bazelrc`

**Comment by iirina** [comment]
Ping, this is still failing

**Comment by iirina** [comment]
cc: @bogatyy @calberti

**Comment by drpngx** [comment]
@gunan who maintains that CI?

**Comment by gunan** [comment]
The CI is maintained by bazel team (also reporters are bazel team :) )
@nealwu @bogatyy Could you take a look?

**Comment by bogatyy** [comment]
Thank you!
We are aware of the issue. The cause is SyntaxNet relying on an outdated Bazel version (0.5.4) because more recent versions introduced breaking changes.
Is there a way to specify the Bazel version we want in Jenkins?

**Comment by vladmos** [comment]
We don't support old versions (at least before 1.0) and encourage updating configs to be compatible with the most recent version. We introduce many breaking changes to make the API as stable as possible once Bazel reaches 1.0. Also at some point Tensorflow or other libraries you use may become incompatible with 0.5.4, then it won't be possible to build the project at all.

I can help with updating SyntaxNet to be compatible with Bazel 0.8. Was there a problem with SyntaxNet configs or configs of one of its dependencies?

**Comment by gunan** [comment]
@av8ramit which dockerfile does the syntaxnet tests run with?
We can update the bazel version on the dockerfile to help with this issue.

**Comment by av8ramit** [comment]
I have a PR, but I'm not sure if this is the right move after @vladmos 's comments. I believe that is the file in question though. @gunan 

https://github.com/tensorflow/models/pull/2962

**Comment by mhlopko** [comment]
Friendly ping, tf_models_syntaxnet has been red on ci.bazel.io for more than a month. As Vlad said, we'll gladly help to fix it. There's a little use in having tf_models_syntaxnet on our ci if it's constantly red...

**Comment by av8ramit** [comment]
I've merged the PR updating the bazel version, hopefully that fixes the issue

**Comment by mhlopko** [comment]
Oh great! Thank you!

**Comment by shubham0704** [comment]
I am facing the same issue  even after the fix of bazel version to latest - 
![screenshot from 2018-01-07 12-49-26](https://user-images.githubusercontent.com/15546524/34647498-2d3208de-f3aa-11e7-8580-c4aea8c4b570.png)

Possibly buggy implementation of py_proto_library - 
https://stackoverflow.com/questions/47688252/tensorflow-trying-to-mutate-a-frozen-object-bazel

**Comment by SaintNazaire** [comment]
Same here.

@jart, thank you for trying to fix this.

This is not a duplicate of #2822 and #2962

Suggest to reopen the issue problem is still there, the error log is almost identical.

Bazel version 0.8.0 AND 0.7.0 AND 0.5.4

> Loading:
> Loading: 0 packages loaded
> Loading: 0 packages loaded
> Loading: 17 packages loaded
>     currently loading: dragnn/protos ... (2 packages)
> Loading: 17 packages loaded
>     currently loading: dragnn/protos ... (2 packages)
> Loading: 17 packages loaded
>     currently loading: dragnn/protos ... (2 packages)
> Loading: 17 packages loaded
>     currently loading: dragnn/protos ... (2 packages)
> Loading: 17 packages loaded
>     currently loading: dragnn/protos ... (2 packages)
> Loading: 17 packages loaded
>     currently loading: dragnn/protos ... (2 packages)
> Loading: 17 packages loaded
>     currently loading: dragnn/protos ... (2 packages)
> Loading: 17 packages loaded
>     currently loading: dragnn/protos ... (2 packages)
> ERROR: /models/research/syntaxnet/dragnn/protos/BUILD:35:1: Traceback (most recent call last):
>         File "/models/research/syntaxnet/dragnn/protos/BUILD", line 35
>                 tf_proto_library_py(name = "data_py_pb2", srcs = ["dat..."])
>         File "/models/research/syntaxnet/syntaxnet/syntaxnet.bzl", line 53, in tf_proto_library_py
>                 py_proto_library(name = name, srcs = srcs, srcs_versi...", <5 more arguments>)
>         File "/root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/external/protobuf_archive/protobuf.bzl", line 374, in py_proto_library
>                 py_libs += [default_runtime]
> trying to mutate a frozen object
> ERROR: /models/research/syntaxnet/dragnn/protos/BUILD:40:1: Traceback (most recent call last):
>         File "/models/research/syntaxnet/dragnn/protos/BUILD", line 40
>                 tf_proto_library_py(name = "trace_py_pb2", srcs = ["tr..."], ..."])
>         File "/models/research/syntaxnet/syntaxnet/syntaxnet.bzl", line 53, in tf_proto_library_py
>                 py_proto_library(name = name, srcs = srcs, srcs_versi...", <5 more arguments>)
>         File "/root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/external/protobuf_archive/protobuf.bzl", line 374, in py_proto_library
>                 py_libs += [default_runtime]
> trying to mutate a frozen object
> ERROR: /models/research/syntaxnet/dragnn/protos/BUILD:46:1: Traceback (most recent call last):
>         File "/models/research/syntaxnet/dragnn/protos/BUILD", line 46
>                 tf_proto_library_py(name = "spec_py_pb2", srcs = ["spe..."])
>         File "/models/research/syntaxnet/syntaxnet/syntaxnet.bzl", line 53, in tf_proto_library_py
>                 py_proto_library(name = name, srcs = srcs, srcs_versi...", <5 more arguments>)
>         File "/root/.cache/bazel/_bazel_root/3b4c7ccb85580bc382ce4a52e9580003/external/protobuf_archive/protobuf.bzl", line 374, in py_proto_library
>                 py_libs += [default_runtime]
> trying to mutate a frozen object
> ERROR: package contains errors: dragnn/protos
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:13:1: First argument of 'load' must be a label and start with either '//', ':', or '@'. Use --incompatible_load_argument_is_label=false to temporarily disable this check.
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:23:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:28:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:33:1: name 'tf_proto_library_py' is not defined
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:38:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:43:1: name 'tf_proto_library_py' is not defined
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:48:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:54:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:59:1: name 'tf_proto_library_py' is not defined
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:64:1: name 'tf_proto_library' is not defined (did you mean 'cc_proto_library'?)
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:69:1: name 'tf_proto_library_py' is not defined
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:773:1: name 'tf_gen_op_libs' is not defined
> ERROR: /models/research/syntaxnet/syntaxnet/BUILD:777:1: name 'tf_gen_op_wrapper_py' is not defined
> ERROR: package contains errors: syntaxnet
> ERROR: error loading package 'syntaxnet': Package 'syntaxnet' contains errors
> INFO: Elapsed time: 13.186s
> FAILED: Build did NOT complete successfully (19 packages loaded)

**Comment by shubham0704** [comment]
@SaintNazaire  I have made a small [repo](https://github.com/shubham0704/syntaxnet-minimal) to test our projects in syntaxnet. Hope it helps :)

**Comment by SaintNazaire** [comment]
Thank you very much @shubham0704, I am using a similar solution though I learned a couple things from your code. This being said my target is to fix the source code to be able to build it from scratch. At this stage I am still a bit scratching my head on how some bit and bobs get to work together but I'm making continuous progress.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
