### ISSUE TITLE
deeplab 

### ISSUE THREAD

**Issue by cuicuizhang1989** [tensorflow/models#3577]
AttributeError: 'module' object has no attribute 'DEFINE_multi_float'
 when run python deeplab/model_test.py , this error happened. how to resolve it, thanks!

**Comment by cuicuizhang1989** [comment]
the problem is solved, as the  tf version needed 1.6

**Comment by ksnzh** [comment]
@cuicuizhang1989 Which python version do you use?

**Comment by YknZhu** [comment]
The root cause should be python gflags version. Please keep it up-to-date.

https://github.com/google/python-gflags/blob/80bcd7d8fcf8db0ab8fa037122a0ea9c7bafc681/gflags/__init__.py#L775

**Comment by shipeng-uestc** [comment]
@YknZhu,I have keep gflags up-to-date.But I still have the error. I use Tf1.3

**Comment by YknZhu** [comment]
ahha sorry tf might depends on its own gflag (now move to absl flag [here](https://github.com/abseil/abseil-py/tree/master/absl/flags)).

The quick fix is to update your tensorflow to 1.6, which should fix it.

**Comment by Air-Fighter** [comment]
I still got the same error in TF 1.10.0
